--DDL문 CREATE, ALTER, DROP
--오라클 대표 데이터 타입 ( VARCHAR2 - 가변문자, CHAR - 고정문자, NUMBER 숫자, DATE - 날짜)

CREATE TABLE DEPT2 (
    DEPT_NO NUMBER(2), -- 정수 2자리
    DEPT_NAME VARCHAR2 (20), -- 최대 20바이트, 가변문자형
    DEPT_YN CHAR(1), -- 1바이트 고정문자형
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10,3) --10자리, 소수부 3자리
);

DESC DEPT2;

INSERT INTO DEPT2 VALUES (99, 'DEMO', 'Y', SYSDATE, 3.14);
INSERT INTO DEPT2 VALUES (99, 'DEMO', '홍', SYSDATE, 3.14); -- 한글은 2바이트, 데이터입력이 안됨.
SELECT * FROM DEPT2;
COMMIT;
------------------------------------------------------------
-- 컬럼 추가
ALTER TABLE DEPT2 ADD (DEPT_COUNT NUMBER(3));
--열 이름 변경
ALTER TABLE DEPT2 RENAME COLUMN DEPT_COUNT TO EMP_COUNT;
--열 수정 (타입변경)
ALTER TABLE DEPT2 MODIFY (EMP_COUNT NUMBER(10));
DESC DEPT2;

--열 삭제
ALTER TABLE DEPT2 DROP COLUMN EMP_COUNT;

SELECT * FROM DEPT2;
--테이블 삭제
DROP TABLE DEPT2;
--DROP TABLE DEPT2 CASCADE 제약조건명; --제약조건 FK도 삭제, 테이블도 삭제

------------------------------------------------------
--제약 조건
SELECT * FROM USER_CONSTRAINTS ORDER BY TABLE_NAME;
--제약 조건 이름이 자동생성
CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2) PRIMARY KEY,
    DEPT_NAME VARCHAR(20) NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, --제약조건 X (컬럼의 기본값)
    DEPT_PHONE VARCHAR2(20) UNIQUE,
    DEPT_BONUS NUMBER(10) CHECK(DEPT_BONUS>0), 
    LOCA NUMBER(4) REFERENCES LOCATIONS(LOCATION_ID) --FK
);
DROP TABLE DEPTS2;
--제약 조건 이름 지정
CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2) CONSTRAINT DEPT2_PK PRIMARY KEY,
    DEPT_NAME VARCHAR(20) CONSTRAINT DEPT2_NAME_NN NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, --제약조건 X (컬럼의 기본값)
    DEPT_PHONE VARCHAR2(20) CONSTRAINT DEPT2_PHONE_UK UNIQUE,
    DEPT_BONUS NUMBER(10) CONSTRAINT DEPT2_BONUS_CK CHECK(DEPT_BONUS>0), 
    LOCA NUMBER(4) CONSTRAINT DEPT2_LOCA_FK REFERENCES LOCATIONS(LOCATION_ID) --FK
);
DESC DEPTS2;
DROP TABLE DEPTS2;

CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2) ,
    DEPT_NAME VARCHAR(20) NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, --제약조건 X (컬럼의 기본값)
    DEPT_PHONE VARCHAR2(20) ,
    DEPT_BONUS NUMBER(10), 
    LOCA NUMBER(4),
    CONSTRAINT DEPT_PK PRIMARY KEY(DEPT_NO/*,DEPT_NAME*/), --2컬럼이 하나로 묶여서 PK로 => 슈퍼키
    CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
    CONSTRAINT DEPT_BONUS_CK CHECK(DEPT_BONUS>0),
    CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)
);
DROP TABLE DEPTS2;
DESC DEPTS2;
INSERT INTO DEPTS2 VALUES (NULL, 'HONG',SYSDATE,'010.....',10000,1000);
INSERT INTO DEPTS2 VALUES (10, 'HONG',SYSDATE,'010.....',10000,1000);
INSERT INTO DEPTS2 VALUES (10, 'HONG',SYSDATE,'010.....',10000,1000);
--참조무결성 (참조테이블의 PK가 아닌 값이 FK에 들어갈 수 없음) 
-- 500은 LOCATIONS의 PK가 아니기 때문에 parent key not found 오류가 발생
INSERT INTO DEPTS2 VALUES (20, 'HONG', SYSDATE, '010....',10000,500);
--도메인 무결성 (값은 컬럼에 정의된 값이어야 한다.)
--  -1000은 DEPT_BONUS의 CHECK 제약조건에 위배되기에 행이 삽입될 수 없다.
INSERT INTO DEPTS2 VALUES (30, 'HONG', SYSDATE, '010222222',-1000,1000);

SELECT * FROM LOCATIONS;
-------------------------------------------------------------------------
-- 제약조건을 추가 or 삭제 
CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2) ,
    DEPT_NAME VARCHAR(20) ,
    DEPT_DATE DATE DEFAULT SYSDATE, --제약조건 X (컬럼의 기본값)
    DEPT_PHONE VARCHAR2(20) ,
    DEPT_BONUS NUMBER(10), 
    LOCA NUMBER(4)
--    CONSTRAINT DEPT_PK PRIMARY KEY(DEPT_NO/*,DEPT_NAME*/), --2컬럼이 하나로 묶여서 PK로 => 슈퍼키
--    CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
--    CONSTRAINT DEPT_BONUS_CK CHECK(DEPT_BONUS>0),
--    CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)
);
--제약 조건은 수정이 없음.
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_PK PRIMARY KEY (DEPT_NO);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_BONUS_CK CHECK (DEPT_BONUS >0);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS (LOCATION_ID);

--NOT NULL은 MODIFY 문장으로 수정한다.
ALTER TABLE DEPTS2 MODIFY DEPT_NAME VARCHAR2(20) NOT NULL;
--제약 조건 삭제
ALTER TABLE DEPTS2 DROP CONSTRAINT DEPT_LOCA_FK;
DROP TABLE DEPTS2;

------------------------------------------------------------------------
--연습 문제

CREATE TABLE MEM (
    M_NAME VARCHAR2(20) NOT NULL,
    M_NUM NUMBER(10) CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY,
    REG_DATE DATE NOT NULL CONSTRAINT MEM_REGDATE_UK UNIQUE,
    GENDER CHARACTER(1) CHECK (GENDER IN ('M','F')),
    LOCA NUMBER(10) CONSTRAINT MEM_LOCA_LOC_LOCID_FK REFERENCES LOCATIONS(LOCATION_ID)
);

INSERT INTO MEM VALUES (
    'AAA', 1, '2018-07-01', 'M',1800
);
INSERT INTO MEM VALUES (
    'BBB', 2, '2018-07-02', 'F',1900
);
INSERT INTO MEM VALUES (
    'CCC', 3, '2018-07-03', 'M',2000
);
INSERT INTO MEM VALUES (
    'DDD', 4, SYSDATE, 'M',2000
);
COMMIT;
SELECT M_NAME,M_NUM,STREET_ADDRESS,L.LOCATION_ID
FROM MEM M
JOIN LOCATIONS L
ON LOCA = LOCATION_ID
ORDER BY M_NUM;















