-- 오라클의 주석은 하이픈 2개로 표현한다.
/*
여러줄 주석은 자바와 같다.
오라클은 대소문자 구분을 하지 않는다.
*/
SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, EMAIL, HIRE_DATE FROM EMPLOYEES;
SELECT JOB_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

--연산
-- 컬럼을 조회하는 위치에서 * / + -
SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY+SALARY*0.1 연산결과 FROM EMPLOYEES;

--NULL
SELECT FIRST_NAME, COMMISSION_PCT FROM EMPLOYEES;

--Alias   as
SELECT FIRST_NAME AS 이름, 
       LAST_NAME AS 성, 
       SALARY 급여, 
       SALARY+SALARY*0.1 총급여
FROM EMPLOYEES;

--리터럴 문자 스트링과 연결 연산자 || 로 연결한다 
-- 문자열 안에서 ' 를 사용하고 싶으면 '' 연달아 사용
SELECT FIRST_NAME || ' ' || LAST_NAME || '''s SALARY IS $' ||SALARY 
AS "Employee Details"
FROM EMPLOYEES;

--DISTINCT 키워드
--FIRST_NAME, DEPARTMENT_ID 둘 다 동일한 중복행 제거
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES; 
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DEPARTMENT_ID FROM EMPLOYEES;
--ROWID(데이터의 주소), ROWNUM(조회된 순서)
SELECT ROWNUM, ROWID, EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES;

