--숫자 함수
--ROUND() 반올림
SELECT 45.123 FROM DUAL;
SELECT ROUND(45.523 ,2), ROUND(45.523), ROUND(45.523,-1) FROM DUAL;
--TRUNC() -절삭 
SELECT TRUNC(45.523 ,2), TRUNC(45.523), TRUNC(45.523,-1) FROM DUAL;
--CEIL() 올림 , FLOOR() 내림 
SELECT CEIL(3.14), FLOOR(3.14) FROM DUAL;
--MOD() 나머지
SELECT ROUND(5/3,2) 몫 , MOD(5,3)나머지 FROM DUAL;


SELECT FIRST_NAME, ROUND((SYSDATE - HIRE_DATE)/7) AS "WEEKS"
FROM EMPLOYEES WHERE DEPARTMENT_ID = 60;

---------------------------------------------------------------------
-- 날짜함수
SELECT SYSDATE FROM DUAL; --년/월/일
SELECT SYSTIMESTAMP FROM DUAL; -- 시 분 초 millisecond을 포함한 상세 시간

--날짜 연산 => 기준이 일 수
SELECT SYSDATE +10 FROM DUAL; -- +10일 
SELECT SYSDATE -10 FROM DUAL; -- -10일
SELECT ROUND(SYSDATE - HIRE_DATE) FROM EMPLOYEES; --일 수
SELECT (SYSDATE - HIRE_DATE)/7 WEEKS FROM EMPLOYEES;
SELECT ROUND((SYSDATE - HIRE_DATE)/365,1) YEARS FROM EMPLOYEES;
SELECT TRUNC ( (SYSDATE-HIRE_DATE) / 365) *12 MONTH FROM EMPLOYEES;

--날짜의 반올림(ROUND), 절삭(TRUNC)
SELECT ROUND ( SYSDATE ) FROM DUAL;
SELECT ROUND ( SYSDATE , 'DAY' ) FROM DUAL; -- 해당 주의 일요일로 
SELECT ROUND ( SYSDATE, 'MONTH' ) FROM DUAL; --월에 대한 반올림 
SELECT ROUND ( SYSDATE, 'YEAR' ) FROM DUAL; -- 년에 대한 반올림

SELECT TRUNC(SYSDATE) FROM DUAL;
SELECT TRUNC ( SYSDATE, 'DAY' ) FROM DUAL; --해당 주의 일요일 
SELECT TRUNC ( SYSDATE, 'MONTH' ) FROM DUAL;
SELECT TRUNC ( SYSDATE, 'YEAR' ) FROM DUAL;






