CREATE TABLE MOVIE (
MOVIE_NO VARCHAR2(99) CONSTRAINT MOVIENO_PK PRIMARY KEY,
MOVIE_NAME VARCHAR2(99) NOT NULL,
MOVIE_RUN VARCHAR2(99) NOT NULL,
MOVIE_PRICE NUMBER(5) NOT NULL
);

CREATE TABLE HMEMBER (
H_ID   VARCHAR2(100)   CONSTRAINT HID_PK PRIMARY KEY,
H_NAME   VARCHAR2(100) NOT NULL,

H_PHONE   VARCHAR2(100) NOT NULL,

H_PASSWORD   VARCHAR2(100) NOT NULL
);

CREATE TABLE THEATER(
THEATER_NUM VARCHAR2(99)           CONSTRAINT THEATER_PK PRIMARY KEY,  --PK
THEATER_SEAT VARCHAR2(99)           NOT NULL,
MOVIE_NO VARCHAR2(99)                 CONSTRAINT THEATER_MOVIENO_FK REFERENCES MOVIE ( MOVIE_NO )-- FK
);

CREATE TABLE PAYMENT (
PAY_NUM NUMBER(15) CONSTRAINT PAYMENT_PK PRIMARY KEY);

CREATE TABLE TICKETORDER (
T_ORDERNO VARCHAR2(99) CONSTRAINT ORDER_PK PRIMARY KEY,
H_ID VARCHAR2(99) CONSTRAINT ORDER_HID_FK REFERENCES HMEMBER(H_ID),
PAY_NUM NUMBER(15) CONSTRAINT PAYMENT_FK REFERENCES PAYMENT(PAY_NUM),
TORDERSEAT VARCHAR2(99)
);

CREATE TABLE SCHEDULE (
SCH_NO VARCHAR2(99) CONSTRAINT SCHEDULE_SCHNO_PK PRIMARY KEY,
SCH_TIME VARCHAR2(10) NOT NULL,
MOVIE_NO VARCHAR2(99) CONSTRAINT SCHEDULE_MOVIENO_FK REFERENCES MOVIE(MOVIE_NO),
T_ORDERNO VARCHAR2(10) CONSTRAINT SCHEDULE_ORDERNO_FK REFERENCES TICKETORDER(T_ORDERNO)
);

CREATE SEQUENCE MOVIE_SEQ NOCACHE;
SELECT MOVIE_SEQ.NEXTVAL FROM DUAL;

INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'범죄도시1',121,12000);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'범죄도시2',132,11500);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'철수는못말려',110,15000);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'짱구도못말려',130,12500);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'유리는사람을말려',147,16000);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'사랑방열매따기','2시간 7분',14000);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'공부가싫어요','3시간 7분',8500);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'공부가왜싫어요?','1시간 49분',9000);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'왜일거같은데','40분',6500);
INSERT INTO MOVIE VALUES('MOV'||LPAD(MOVIE_SEQ.NEXTVAL,3,0),'김민철수때문에','1시간 20분',72000);
SELECT * FROM MOVIE;

COMMIT;

CREATE SEQUENCE HMEMBER_SEQ NOCACHE;

INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'박수정','010-1111-1111','tnwjd000');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'김혜민','010-1111-1112','tnwjd001');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'김민철','010-1111-1113','tnwjd002');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'박동훈','010-1111-1114','tnwjd003');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'박인욱','010-1111-1115','tnwjd004');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'차은우','010-1111-1116','tnwjd005');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'홍길동','010-1111-1117','tnwjd006');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'홍길자','010-1111-1118','tnwjd007');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'이순신','01088884455','tnwjd008');
INSERT INTO HMEMBER VALUES('ID'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'신사임당','01051434545','tnwjd009');

COMMIT;

INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'A-01', 'MOV001');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'B-01','MOV002');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'C-01','MOV003');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'A-02','MOV004');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'B-02','MOV005');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'C-02','MOV006');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'A-03','MOV007');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'B-03','MOV008');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'C-03','MOV009');
INSERT INTO THEATER VALUES('THEA'||LPAD(HMEMBER_SEQ.NEXTVAL,4,0),'A-04','MOV010');
COMMIT;

INSERT INTO PAYMENT VALUES (01);
INSERT INTO PAYMENT VALUES (02);
INSERT INTO PAYMENT VALUES (03);
INSERT INTO PAYMENT VALUES (04);
INSERT INTO PAYMENT VALUES (05);
INSERT INTO PAYMENT VALUES (06);
INSERT INTO PAYMENT VALUES (07);
INSERT INTO PAYMENT VALUES (08);
INSERT INTO PAYMENT VALUES (09);
INSERT INTO PAYMENT VALUES (10);
COMMIT;

CREATE SEQUENCE TICKET_SEQ NOCACHE;
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0001',
    01,
    'A-4'
);
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0001',
    01,
    'A-5'
);
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0002',
    02,
    'A-6'
);
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0003',
    03,
    'B-4'
);
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0003',
    04,
    'B-5'
);
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0005',
    05,
    'C-4'
);
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0005',
    06,
    'C-5'
);
INSERT INTO TICKETORDER VALUES (
    'TICK'||LPAD(TICKET_SEQ.NEXTVAL,3,0),
    'ID0007',
    07,
    'D-4'
);
COMMIT;

CREATE SEQUENCE SCHEDULE_SEQ NOCACHE;

INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '10:40', 'MOV001', 'TICK007');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '10:40', 'MOV002', 'TICK008');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '14:20', 'MOV003', 'TICK001');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '14:20', 'MOV004', 'TICK002');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '15:40', 'MOV005', 'TICK007');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '15:40', 'MOV006', 'TICK007');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '12:40', 'MOV007', 'TICK004');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '18:20', 'MOV008', 'TICK005');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '20:10', 'MOV009', 'TICK006');
INSERT INTO SCHEDULE VALUES ('SCH'||LPAD(SCHEDULE_SEQ.NEXTVAL,3,0), '20:10', 'MOV010', 'TICK007');
SELECT * FROM SCHEDULE;
COMMIT;

